// Auto-generated by Supabase CLI — DO NOT EDIT MANUALLY
// Run: npx supabase gen types typescript --project-id <id> > src/lib/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // Placeholder — se completará con supabase gen types
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
        Relationships: unknown[]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      rol_usuario: 'ADMIN' | 'POSTULANTE' | 'RECLUTADOR'
      estado_informe: 'PENDIENTE' | 'LISTO' | 'ERROR'
      estado_postulacion: 'ENVIADA' | 'VISTO' | 'PROCESO_FINALIZADO' | 'CERRADA'
      carga_horaria: 'TIEMPO_COMPLETO' | 'MEDIO_TIEMPO' | 'POR_HORAS_FREELANCE'
      ubicacion: 'REMOTO' | 'HIBRIDO' | 'LOCALIDADES'
      nivel_idioma: 'BASICO' | 'INTERMEDIO' | 'AVANZADO' | 'NATIVO'
      tipo_energetico_hd: 'Generator' | 'Manifesting Generator' | 'Projector' | 'Manifestor' | 'Reflector'
      perfil_hd: '1/3' | '1/4' | '2/4' | '2/5' | '3/5' | '3/6' | '4/6' | '4/1' | '5/1' | '5/2' | '6/2' | '6/3'
      autoridad_hd: 'Emotional' | 'Sacral' | 'Splenic' | 'Ego/Heart' | 'Self-Projected' | 'Mental/Environmental' | 'Lunar'
      estrategia_hd: 'To Respond' | 'To Inform' | 'Wait for the Invitation' | 'Wait a Lunar Cycle'
      tipo_pregunta_preselector: 'OPCIONES' | 'TEXTO_LIBRE'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
